<a href="https://colab.research.google.com/github/subishinu/Brid_Subi/blob/main/PreprocessingTutorialDay2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
import numpy as np
import matplotlib.pyplot as mtp
import pandas as pd

In [43]:
# Importing dataset
data = pd.read_csv('dataset.csv')
data.shape

(10, 4)

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Country    10 non-null     object 
 1   Age        9 non-null      float64
 2   Salary     9 non-null      float64
 3   Purchased  10 non-null     object 
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [45]:
data.head()

Country   Age   Salary Purchased
0    India  38.0  68000.0        No
1   France  43.0  45000.0       Yes
2  Germany  30.0  54000.0        No
3   France  48.0  65000.0        No
4  Germany  40.0      NaN       Yes

In [46]:
data.describe()

Age        Salary
count   9.000000      9.000000
mean   41.111111  65222.222222
std     6.900081  14104.766728
min    30.000000  45000.000000
25%    37.000000  54000.000000
50%    40.000000  65000.000000
75%    48.000000  77000.000000
max    50.000000  88000.000000

## **Extracting independent variable:**

In [47]:
x=data.iloc[:,:-1].values

In [48]:
x

array([['India', 38.0, 68000.0],
       ['France', 43.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['France', 48.0, 65000.0],
       ['Germany', 40.0, nan],
       ['India', 35.0, 58000.0],
       ['Germany', nan, 53000.0],
       ['France', 49.0, 79000.0],
       ['India', 50.0, 88000.0],
       ['France', 37.0, 77000.0]], dtype=object)

## **Extracting dependent variable**

In [49]:
y = data.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## **Handling Missing data**

In [50]:
# Replacing missing data with the mean value
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy='mean')


# Fitting imputer object to the independent variable x
imputer = imputer.fit(x[:,1:3])

#Replacing missing data with the calculated mean value
x[:,1:3] = imputer.transform(x[:,1:3])

x

array([['India', 38.0, 68000.0],
       ['France', 43.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['France', 48.0, 65000.0],
       ['Germany', 40.0, 65222.22222222222],
       ['India', 35.0, 58000.0],
       ['Germany', 41.111111111111114, 53000.0],
       ['France', 49.0, 79000.0],
       ['India', 50.0, 88000.0],
       ['France', 37.0, 77000.0]], dtype=object)

## **Encoding Categorical data**

In [51]:
# for country variable
from sklearn.preprocessing import LabelEncoder
label_encoder_x=LabelEncoder()
x[:,0]=LabelEncoder().fit_transform(x[:,0])
x

array([[2, 38.0, 68000.0],
       [0, 43.0, 45000.0],
       [1, 30.0, 54000.0],
       [0, 48.0, 65000.0],
       [1, 40.0, 65222.22222222222],
       [2, 35.0, 58000.0],
       [1, 41.111111111111114, 53000.0],
       [0, 49.0, 79000.0],
       [2, 50.0, 88000.0],
       [0, 37.0, 77000.0]], dtype=object)

In [52]:
# Dummy encoding for Country variable
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

col_trans =ColumnTransformer(transformers=[('onehot',OneHotEncoder(),[0])],remainder='passthrough')

#fit and transform data
x_transformed = col_trans.fit_transform(x)

x_transformed




array([[0.0, 0.0, 1.0, 38.0, 68000.0],
       [1.0, 0.0, 0.0, 43.0, 45000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 48.0, 65000.0],
       [0.0, 1.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 41.111111111111114, 53000.0],
       [1.0, 0.0, 0.0, 49.0, 79000.0],
       [0.0, 0.0, 1.0, 50.0, 88000.0],
       [1.0, 0.0, 0.0, 37.0, 77000.0]], dtype=object)

In [53]:
# for purchase variable
label_encoder_y= LabelEncoder()
y=LabelEncoder().fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

## **Splitting the Dataset into the training set and test set**